name: Destroy Terraform Resources

on:
  workflow_dispatch:
    # Optional: Trigger den Workflow manuell von GitHub Actions
    inputs:
      confirmation:
        description: 'Bestätige das Löschen aller Ressourcen'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.0  # Stelle sicher, dass du die gewünschte Terraform-Version angibst

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: eu-central-1

      - name: Terraform Destroy
        if: ${{ github.event.inputs.confirmation == 'yes' }}
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: eu-central-1

      - name: Terraform Destroy Confirmation
        if: ${{ github.event.inputs.confirmation != 'yes' }}
        run: echo "Löschen der Ressourcen abgebrochen. Bestätige das Löschen mit 'yes' in den Workflow-Inputs."
