name: Terraform deploy

on:
  workflow_dispatch:  # Ermöglicht manuelles Triggern des Workflows über GitHub UI

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3  # Stellen Sie sicher, dass diese Version korrekt ist

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      # Initialize Terraform
      - name: Terraform init
        run: terraform init 

      # Format check
      - name: Terraform fmt check
        run: terraform fmt -check

      # Validate Terraform configuration
      - name: Terraform validate
        run: terraform validate

      # Terraform plan
      - name: Terraform plan
        run: terraform plan

      # Apply Terraform configuration (only if you want to apply automatically)
      - name: Terraform apply
        run: terraform apply -auto-approve

      # Destroy Terraform resources (optional, uncomment if needed)
      # - name: Terraform destroy
      #   run: terraform destroy -auto-approve
      #   working-directory: terraform
