name: Terraform Deploy 2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Format Check
        run: terraform fmt --check
        # Optional: Fail the workflow if `terraform fmt --check` finds formatting issues
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        # Optional: Save the plan output as an artifact for review
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve
        # Optional: Run this step only on specific branches or tags
        if: github.ref == 'refs/heads/main'

    #   - name: Terraform Destroy
    #     run: terraform destroy -auto-approve
        # Optional: Run this step only on specific branches or tags
        # if: github.ref == 'refs/heads/cleanup'
